apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-sejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-sejs
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-sejs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-sejs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-sejs
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-psaz-tenant/rhtap-demo-app/hacbs-test-project-sejs@sha256:ff7ed9f135bd0f1219b4baa5daa74f1398001ed162705e009ca8e1d40d693cbd
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
